### ISSUE TITLE
DeleteFromGallery

### ISSUE THREAD

**Issue by soqman** [yasirkula/UnityNativeGallery#14]
How to delete file? Why method DeleteFromGallery cant work in new version?

**Comment by yasirkula** [comment]
I removed it because of three reasons:

- it didn't support iOS
- save functions don't return the path of the saved media and thus, if filenameFormatted contains {0}, developer can't really know the path to pass as parameter to DeleteFromGallery
- apps in the Store usually access the Gallery to save media only; and I also think that user should delete unwanted images manually from the Gallery

Nevertheless, you can add the following function to NativeGallery.cs to bring it back:

```csharp
public static void DeleteFromGallery( string path, bool isImage )
{
	if( !File.Exists( path ) )
		throw new FileNotFoundException( "File not found at " + path );

	File.Delete( path );

#if !UNITY_EDITOR && UNITY_ANDROID
	AJC.CallStatic( "MediaDeleteFile", Context, path, isImage );
#endif

	Debug.Log( "Deleted from gallery: " + path );
}
```

**Comment by Madorath** [comment]
I need to delete from the gallery, I tried this solution but get this error:

```
AndroidJavaException: java.lang.NoSuchMethodError: no static method with name='MediaDeleteFile' signature='(Lcom.unity3d.player.UnityPlayerActivity;Ljava/lang/String;Z)V' in class Ljava.lang.Object;
11-28 10:57:18.917 31697 31728 E Unity   : java.lang.NoSuchMethodError: no static method with name='MediaDeleteFile' signature='(Lcom.unity3d.player.UnityPlayerActivity;Ljava/lang/String;Z)V' in class Ljava.lang.Object;
11-28 10:57:18.917 31697 31728 E Unity   :      at com.unity3d.player.ReflectionHelper.getMethodID(Unknown Source:226)
11-28 10:57:18.917 31697 31728 E Unity   :      at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
11-28 10:57:18.917 31697 31728 E Unity   :      at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
11-28 10:57:18.917 31697 31728 E Unity   :      at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
11-28 10:57:18.917 31697 31728 E Unity   :      at android.os.Handler.dispatchMessage(Handler.java:102)
11-28 10:57:18.917 31697 31728 E Unity   :      at android.os.Looper.loop(Looper.java:236)
11-28 10:57:18.917 31697 31728 E Unity   :      at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
11-28 10:57:18.917 31697 31728 E Unity   :   at UnityEngine._AndroidJNIHelper.GetMethodID (System.IntPtr jclass, System.String methodName, System.String signature, System.Boolean isStatic) [0x0003c] in /home/bokken/buildslave/unity/build/Modules/AndroidJNI/AndroidJa
```

How can I fix this?

**Comment by yasirkula** [comment]
bool isImage has changed to int mediaType (which is int value of MediaType enum).

**Comment by Madorath** [comment]
Thank you for the quick reply, I no longer get that error now, but when I try to delete a file in my gallery it remains thereand the only information I get from Android is this:

`MediaProvider: Deleted 0 0 0 0 0 0 0 items on external_primary due to`

Am I having permission problems? I've made sure to give write permissions on external.

**Comment by yasirkula** [comment]
Yes you might be having permission issues. You may not be able to remove images that aren't saved to Gallery by your app on newest Android versions. I'm not talking with certainty because I haven't researched this particular feature in detail. I also don't know what the path that you've passed to the function looks like and if it points to a valid file.

**Comment by Madorath** [comment]
Yeah, I've tested to see if it lets me delete a file that I have created in the same path, it lets me do so, but with the same path and a file that was not created by the app it is not able to delete it, do you have any ideas as to how I would get those permissions?

**Comment by yasirkula** [comment]
This seems useful: https://stackoverflow.com/a/65437141/2373034. One key point here is that you need the Uri of the media file, not its raw filepath. That should be achievable with something like this: https://stackoverflow.com/a/11603841/2373034

**Comment by Madorath** [comment]
How do I use the MediaStore functions in Unity? I have seen similar posts like that, but I do not know how to implement them.

**Comment by yasirkula** [comment]
This is native code. You can either write plugins in Android Studio or call the functions with AndroidJavaClass and AndroidJavaObject.

**Comment by Madorath** [comment]
I've been looking into this and I'm using an AndroidJavaClass to try and call CreateDeleteRequest which has this prototype:
`
public static Android.App.PendingIntent CreateDeleteRequest (Android.Content.ContentResolver resolver, System.Collections.Generic.ICollection<Android.Net.Uri> uris);
` 
But I don't know how to create this ContentResolver object. How do I access this within Unity?

**Comment by yasirkula** [comment]
Via UnityPlayerActivity's getContentResolver function, similar to this in native code where context's value is equal to NativeGallery.Context in C#-side: https://github.com/yasirkula/UnityNativeGallery/blob/6f11f15a0bd38a107183ced511876f8e287ae16d/.github/AAR%20Source%20(Android)/java/com/yasirkula/unity/NativeGallery.java#L129

**Comment by gh-rudr** [comment]
Is delete functionality still not supported for iOS @yasirkula

**Comment by yasirkula** [comment]
@gh-rudr Yes :-]
