### ISSUE TITLE
ExifInterface: Invalid image: ExifInterface got an unsupported image format file

### ISSUE THREAD

**Issue by czadam** [yasirkula/UnityNativeGallery#213]
**Description of the bug**

Exception is thrown, when trying to save image to gallery on android. (NativeGallery.SaveToGalleryInternal is causing the excpetion)

**Platform specs**

Please provide the following info if this is a Unity 3D repository.

- Unity version: *2019.4.21f1*
- Platform: *Android 10*
- Device: *more devices (LG G7 Thinq for example)*
- How did you download the plugin: * Asset Store*

**Additional info**

```
2021-08-04 13:55:38.174 27703-27811/com.project W/ExifInterface: Invalid image: ExifInterface got an unsupported image format file(ExifInterface supports JPEG and some RAW image formats only) or a corrupted JPEG file to ExifInterface.
    java.io.IOException: Invalid byte order: 0
        at android.media.ExifInterface.readByteOrder(ExifInterface.java:3180)
        at android.media.ExifInterface.isOrfFormat(ExifInterface.java:2495)
        at android.media.ExifInterface.getMimeType(ExifInterface.java:2373)
        at android.media.ExifInterface.loadAttributes(ExifInterface.java:1786)
        at android.media.ExifInterface.initForFilename(ExifInterface.java:2352)
        at android.media.ExifInterface.<init>(ExifInterface.java:1394)
        at com.yasirkula.unity.NativeGalleryUtils.GetImageOrientation(NativeGalleryUtils.java:262)
        at com.yasirkula.unity.NativeGallery.SaveMedia(NativeGallery.java:70)
        at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
        at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
        at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:214)
        at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
2021-08-04 13:55:38.298 27703-28175/com.project I/native: I0804 13:55:38.298874   28175 viwls_optimization.cc:977] Skip Lite-COM due to a significant calibration change.
2021-08-04 13:55:38.349 27703-27811/com.project D/Unity: Saved media to: content://media/external/images/media/34481
2021-08-04 13:55:38.365 27703-27811/com.project I/Unity: Permission result: Granted
```

**Comment by yasirkula** [comment]
Can I see your code?

**Comment by czadam** [comment]
Nevermind, the problem seemed to be that the existingMediaPath and filename were the same.

`public static Permission SaveImageToGallery( string existingMediaPath, string album, string filename, MediaSaveCallback callback = null )`
