### ISSUE TITLE
GetVideoProperties return "Invalid image"

### ISSUE THREAD

**Issue by yashs-devstree** [yasirkula/UnityNativeGallery#250]
**Description of the bug**

I added a below code to pick video from the device and after receiving callback I'm fetching thumbnail and video's properties. I'm getting thumbnail but I'm receiving "Invalid image" and Exif related warnings in log-cat for video properties.

Here is my code

NativeGallery.Permission permission = NativeGallery.GetVideoFromGallery((path) =>
		{
			Debug.Log("Video Path: " + path);
			if (path != null)
			{
				Texture2D texture2D = NativeGallery.GetVideoThumbnail(videoPath: path, maxSize: -1, captureTimeInSeconds: -1.0, markTextureNonReadable: false);
				NativeGallery.VideoProperties videoProperties = NativeGallery.GetVideoProperties(videoPath: path);
				Debug.Log("Video Properties: " + JsonUtility.ToJson(videoProperties));
			}
		}, "Select a video", "video/*");

**Platform specs**

- Unity version: 2021.3.0f1
- Platform: Android, iOS(Not Tested yet)
- Device: Redmi Note 7 Pro, Android 10
- How did you download the plugin: Asset Store

**Additional info**

2022-06-28 11:13:47.527 2320 2320 Verbose MediaRouter Selecting route: RouteInfo{ name=Phone, description=null, status=null, category=RouteCategory{ name=System types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
2022-06-28 11:13:47.531 2320 2396 Debug AudioManager getStreamVolume isRestricted mode = 0
2022-06-28 11:13:47.534 2320 2396 Info Unity Video Path: /storage/emulated/0/Movies/Instagram/VID_23950609_115450_710.mp4
2022-06-28 11:13:47.534 2320 2396 Info Unity CreationDemo:<GetVideo>b__4_0(String)
2022-06-28 11:13:47.534 2320 2396 Info Unity NativeGalleryNamespace.NGMediaReceiveCallbackAndroid:MediaReceiveCallback(String)
2022-06-28 11:13:47.534 2320 2396 Info Unity 
2022-06-28 11:13:48.041 2320 2396 Warn BpBinder Slow Binder: BpBinder transact took 371ms, interface=android.media.IMediaMetadataRetriever, code=5 oneway=false
2022-06-28 11:13:48.132 2320 2396 Warn ExifInterface Invalid image: ExifInterface got an unsupported image format file(ExifInterface supports JPEG and some RAW image formats only) or a corrupted JPEG file to ExifInterface.
2022-06-28 11:13:48.132 2320 2396 Warn ExifInterface java.io.IOException: Invalid byte order: ffff8950
2022-06-28 11:13:48.132 2320 2396 Warn ExifInterface 	at android.media.ExifInterface.readByteOrder(ExifInterface.java:3128)
2022-06-28 11:13:48.132 2320 2396 Warn ExifInterface 	at android.media.ExifInterface.isOrfFormat(ExifInterface.java:2443)
2022-06-28 11:13:48.132 2320 2396 Warn ExifInterface 	at android.media.ExifInterface.getMimeType(ExifInterface.java:2321)
2022-06-28 11:13:48.132 2320 2396 Warn ExifInterface 	at android.media.ExifInterface.loadAttributes(ExifInterface.java:1755)
2022-06-28 11:13:48.132 2320 2396 Warn ExifInterface 	at android.media.ExifInterface.initForFilename(ExifInterface.java:2303)
2022-06-28 11:13:48.132 2320 2396 Warn ExifInterface 	at android.media.ExifInterface.<init>(ExifInterface.java:1386)
2022-06-28 11:13:48.132 2320 2396 Warn ExifInterface 	at com.yasirkula.unity.NativeGalleryUtils.GetImageOrientation(NativeGalleryUtils.java:321)
2022-06-28 11:13:48.132 2320 2396 Warn ExifInterface 	at com.yasirkula.unity.NativeGalleryUtils.LoadImageAtPath(NativeGalleryUtils.java:434)
2022-06-28 11:13:48.132 2320 2396 Warn ExifInterface 	at com.yasirkula.unity.NativeGallery.LoadImageAtPath(NativeGallery.java:399)
2022-06-28 11:13:48.132 2320 2396 Warn ExifInterface 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
2022-06-28 11:13:48.132 2320 2396 Warn ExifInterface 	at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
2022-06-28 11:13:48.132 2320 2396 Warn ExifInterface 	at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
2022-06-28 11:13:48.132 2320 2396 Warn ExifInterface 	at android.os.Handler.dispatchMessage(Handler.java:103)
2022-06-28 11:13:48.132 2320 2396 Warn ExifInterface 	at android.os.Looper.loop(Looper.java:224)
2022-06-28 11:13:48.132 2320 2396 Warn ExifInterface 	at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
2022-06-28 11:13:48.198 2320 2396 Info Unity Video Properties: {}
2022-06-28 11:13:48.198 2320 2396 Info Unity CreationDemo:<GetVideo>b__4_0(String)
2022-06-28 11:13:48.198 2320 2396 Info Unity NativeGalleryNamespace.NGMediaReceiveCallbackAndroid:MediaReceiveCallback(String)
2022-06-28 11:13:48.198 2320 2396 Info Unity

**Comment by yasirkula** [comment]
The warning comes from LoadImageAtPath which is called from GetVideoThumbnail. I'd say simply ignore this warning if there are no visible issues it causes.

**Comment by yashs-devstree** [comment]
Okay got it. But I'm not getting Video Properties for any of the videos I select. Can you help me with that?

**Comment by yasirkula** [comment]
ToString method isn't overwritten in VideoProperties struct, you need to debug its properties explicitly instead of debugging the struct itself.

**Comment by yashshah1294** [comment]
Okay got it. Thank you for your reply and providing such great assets.

**Comment by yashs-devstree** [comment]
Okay got it. Thank you for your reply and providing such great assets.
