### ISSUE TITLE
crash in android13 miui14.0.28 by RedMiK60 device

### ISSUE THREAD

**Issue by changehong12** [yasirkula/UnityNativeGallery#301]
request the permission dialog, and crash in 5s in android13 miui14.0.28 by RedMiK60 device

- Unity version: *e.g. 2021.3.30f1*
- Platform: Android
- Device: RedMi K60, Android 13, miui 14.0.28
**Additional info**
dumpStackTraces exp is 
                                                                                                    java.util.concurrent.TimeoutException
                                                                                                    	at java.util.concurrent.FutureTask.get(FutureTask.java:204)
                                                                                                    	at com.miui.daemon.mqsas.utils.scout.ScoutManager.dumpStackTraces(ScoutManager.java:825)
                                                                                                    	at com.miui.daemon.mqsas.utils.scout.ScoutManager.appScoutProcess(ScoutManager.java:302)
                                                                                                    	at com.miui.daemon.mqsas.MQSService$10.run(MQSService.java:930)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
2023-11-08 15:11:51.754  8067-9328  ScoutManager            com.miui.daemon                      E  dumpStackTraces fail
2023-11-08 15:11:51.754  8067-9328  MIUIScout App           com.miui.daemon                      E  resend signal 3 to Pid:28586
2023-11-08 15:11:51.760  9347-9347  mqsasd                  pid-9347                             D  mqsasd cmdtool *** (kill): -3,28586
2023-11-08 15:11:51.786   967-981   mqsasd                  mqsasd                               E  mqsasd cmdtool *** kill: Exit code 1
Please check Logcat (Android) or Xcode console (iOS) for any meaningful error messages and include them here.

**Comment by yasirkula** [comment]
Thank you for the stacktrace. I couldn't find useful info there though, unfortunately. Could you try RequestPermissionAsync instead?

**Comment by changehong12** [comment]
i change the permission request to async！ and have already been solved it ！&nbsp;
Thank！



发自我的iPhone


------------------ Original ------------------
From: yasirkula ***@***.***&gt;
Date: Fri,Nov 10,2023 3:50 AM
To: yasirkula/UnityNativeGallery ***@***.***&gt;
Cc: changehong12 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [yasirkula/UnityNativeGallery] crash in android13 miui14.0.28 byRedMiK60 device (Issue #301)





 
Thank you for the stacktrace. I couldn't find useful info there though, unfortunately. Could you try RequestPermissionAsync instead?

**Comment by yasirkula** [comment]
For future readers: use RequestPermissionAsync instead of RequestPermission.
